In [1]:
import os

print(os.path.abspath(os.curdir))

e:\Data Kuliah\S2 ITS\Semester 5\Sentiment Analysis\IEEE IFS\DroneLog\notebooks

In [2]:
import os
os.chdir("..")

In [3]:
print(os.path.abspath(os.curdir))

e:\Data Kuliah\S2 ITS\Semester 5\Sentiment Analysis\IEEE IFS\DroneLog

#### Filtered Dataset

In [7]:
import os
import pandas as pd

recap_path = 'experiments/recap/final-recap-all.xlsx'
recap_df = pd.read_excel(recap_path)
recap_filtered = recap_df[recap_df['dataset'] == 'filtered']
group_columns = ['encoder', 'scenario']
value_column = 'accuracy'

# Use groupby to group the DataFrame by the specified columns
# Then apply idxmax() to get the index of the maximum value in each group
max_indices = recap_filtered.groupby(group_columns)[value_column].idxmax()

# Use loc to retrieve the corresponding rows based on the indices
max_rows_filtered = recap_filtered.loc[max_indices]
max_rows_filtered

,dataset,encoder,n_layer,n_head,bidirectional,pooling,class_weight,scenario,best_epoch,accuracy,precision,recall,f1_score
5,filtered,gru,3,1,unidirectional,mean,balanced,cross_entropy,5,79.48718,78.64763,79.48718,78.94126
23,filtered,gru,3,1,unidirectional,mean,inverse,focal,5,80.34188,79.62907,80.34188,79.80184
626,filtered,gru,1,1,unidirectional,mean,balanced,multitask-101,8,80.34188,79.92674,80.34188,79.91276
649,filtered,gru,1,1,bidirectional,mean,uniform,multitask-111,8,82.90598,83.77948,82.90598,81.57187
39,filtered,linear,1,1,unidirectional,min,balanced,cross_entropy,4,80.34188,79.92646,80.34188,79.89478
50,filtered,linear,1,1,unidirectional,mean,inverse,focal,9,81.19658,80.93167,81.19658,80.64143
662,filtered,linear,1,1,unidirectional,max,balanced,multitask-101,4,79.48718,78.99369,79.48718,78.88505
677,filtered,linear,1,1,unidirectional,cls,uniform,multitask-111,5,78.63248,77.91836,78.63248,77.32335
60,filtered,lstm,1,1,bidirectional,mean,balanced,cross_entropy,6,80.34188,80.06115,80.34188,79.97951
90,filtered,lstm,1,1,bidirectional,mean,uniform,focal,5,82.90598,82.31917,82.90598,81.92130
708,filtered,lstm,1,1,bidirectional,mean,uniform,multitask-101,7,80.34188,79.85043,80.34188,79.79863
711,filtered,lstm,1,1,unidirectional,mean,uniform,multitask-111,8,82.05128,80.36346,82.05128,80.33055
248,filtered,transformer,3,8,unidirectional,cls,uniform,cross_entropy,7,82.05128,81.77615,82.05128,81.25793
217,filtered,transformer,2,6,unidirectional,max,inverse,focal,6,82.05128,82.01186,82.05128,81.30549
728,filtered,transformer,2,6,unidirectional,cls,balanced,multitask-101,10,82.05128,81.59404,82.05128,81.76265
881,filtered,transformer,3,8,unidirectional,cls,uniform,multitask-111,10,83.76068,85.09686,83.76068,83.18207

In [8]:
import os
import pandas as pd

recap_path = 'experiments/recap/final-recap-all.xlsx'
recap_df = pd.read_excel(recap_path)
recap_unfiltered = recap_df[recap_df['dataset'] == 'unfiltered']
group_columns = ['encoder', 'scenario']
value_column = 'accuracy'

# Use groupby to group the DataFrame by the specified columns
# Then apply idxmax() to get the index of the maximum value in each group
max_indices = recap_unfiltered.groupby(group_columns)[value_column].idxmax()

# Use loc to retrieve the corresponding rows based on the indices
max_rows_unfiltered = recap_unfiltered.loc[max_indices]
max_rows_unfiltered

,dataset,encoder,n_layer,n_head,bidirectional,pooling,class_weight,scenario,best_epoch,accuracy,precision,recall,f1_score
313,unfiltered,gru,1,1,unidirectional,mean,balanced,cross_entropy,5,95.53571,95.75676,95.53571,95.62940
334,unfiltered,gru,3,1,bidirectional,mean,inverse,focal,6,95.98214,96.14281,95.98214,96.01680
956,unfiltered,gru,3,1,bidirectional,mean,inverse,multitask-101,7,95.75893,95.36076,95.75893,95.33074
947,unfiltered,gru,3,1,unidirectional,mean,balanced,multitask-111,8,95.75893,95.74147,95.75893,95.66896
349,unfiltered,linear,1,1,unidirectional,max,balanced,cross_entropy,10,95.53571,95.38942,95.53571,95.35536
371,unfiltered,linear,1,1,unidirectional,min,uniform,focal,7,95.98214,95.98668,95.98214,95.95030
984,unfiltered,linear,1,1,unidirectional,mean,inverse,multitask-101,8,95.08929,94.97642,95.08929,95.01297
995,unfiltered,linear,1,1,unidirectional,min,uniform,multitask-111,7,95.75893,95.66115,95.75893,95.63108
373,unfiltered,lstm,1,1,unidirectional,mean,balanced,cross_entropy,4,95.31250,95.29654,95.31250,95.30129
406,unfiltered,lstm,3,1,bidirectional,mean,uniform,focal,3,95.75893,95.36119,95.75893,95.32969
1002,unfiltered,lstm,2,1,unidirectional,mean,balanced,multitask-101,9,95.31250,95.55785,95.31250,95.38500
1007,unfiltered,lstm,3,1,unidirectional,mean,balanced,multitask-111,10,95.98214,96.00168,95.98214,95.97770
421,unfiltered,transformer,2,6,unidirectional,max,balanced,cross_entropy,4,95.98214,95.91959,95.98214,95.89543
588,unfiltered,transformer,1,4,unidirectional,cls,uniform,focal,9,95.75893,95.79915,95.75893,95.75836
1096,unfiltered,transformer,2,8,unidirectional,min,balanced,multitask-101,10,95.98214,95.91551,95.98214,95.93637
1041,unfiltered,transformer,2,6,unidirectional,cls,balanced,multitask-111,4,96.42857,96.40240,96.42857,96.37425

In [9]:
best_model = pd.concat([max_rows_filtered, max_rows_unfiltered], ignore_index=True)
output_dir = os.path.join('experiments', 'recap')
best_model.to_excel(os.path.join(output_dir, 'best_model.xlsx'), index=False)